//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lookups.Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lookups {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lookups() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lookups.Service.Resources.Lookups", typeof(Lookups).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absences Regulation Already Exist In This Period Before.
        /// </summary>
        public static string Absences_Regulation_IsExists {
            get {
                return ResourceManager.GetString("Absences_Regulation_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Delete Administration With Manager.
        /// </summary>
        public static string Administrative_Has_Manager {
            get {
                return ResourceManager.GetString("Administrative_Has_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Administrative Level couldn&apos;t assign to itself or its childrens.
        /// </summary>
        public static string Administrative_LevelsService_Assign_To_Itself {
            get {
                return ResourceManager.GetString("Administrative_LevelsService_Assign_To_Itself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Administrative Level already exist.
        /// </summary>
        public static string Administrative_LevelsService_IsExists {
            get {
                return ResourceManager.GetString("Administrative_LevelsService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string AdministrativeLevelDto_AdmLevelFL_Length {
            get {
                return ResourceManager.GetString("AdministrativeLevelDto_AdmLevelFL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string AdministrativeLevelDto_AdmLevelSl_Length {
            get {
                return ResourceManager.GetString("AdministrativeLevelDto_AdmLevelSl_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Not Greater Than 10 Characters.
        /// </summary>
        public static string AdministrativeLevelDto_Code_Length {
            get {
                return ResourceManager.GetString("AdministrativeLevelDto_Code_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string AdministrativeLevelDto_Code_Required {
            get {
                return ResourceManager.GetString("AdministrativeLevelDto_Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This adminstrative has employees!.
        /// </summary>
        public static string Adminstrative_CannotDelete {
            get {
                return ResourceManager.GetString("Adminstrative_CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string AllowanceDto_AllowanceFL_Length {
            get {
                return ResourceManager.GetString("AllowanceDto_AllowanceFL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string AllowanceDto_AllowanceSL_Length {
            get {
                return ResourceManager.GetString("AllowanceDto_AllowanceSL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Allowance already exist.
        /// </summary>
        public static string AllowanceService_IsExists {
            get {
                return ResourceManager.GetString("AllowanceService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string AllowanceTypeDto_AllowanceTypeFL_Length {
            get {
                return ResourceManager.GetString("AllowanceTypeDto_AllowanceTypeFL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance Type  is required.
        /// </summary>
        public static string AllowanceTypeDto_AllowanceTypesId_Required {
            get {
                return ResourceManager.GetString("AllowanceTypeDto_AllowanceTypesId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string AllowanceTypeDto_AllowanceTypeSL_Length {
            get {
                return ResourceManager.GetString("AllowanceTypeDto_AllowanceTypeSL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Not Greater Than 10 Characters.
        /// </summary>
        public static string AllowanceTypeDto_Code_Length {
            get {
                return ResourceManager.GetString("AllowanceTypeDto_Code_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string AllowanceTypeDto_Code_Required {
            get {
                return ResourceManager.GetString("AllowanceTypeDto_Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Lang Not Greater Than 50 Characters.
        /// </summary>
        public static string AttachmentsTypeDto_NameFl_Length {
            get {
                return ResourceManager.GetString("AttachmentsTypeDto_NameFl_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Lang Not Greater Than 50 Characters.
        /// </summary>
        public static string AttachmentsTypeDto_NameSl_Length {
            get {
                return ResourceManager.GetString("AttachmentsTypeDto_NameSl_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Delete Default Regulation.
        /// </summary>
        public static string cant_Delete_Default {
            get {
                return ResourceManager.GetString("cant_Delete_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Greater than 10 digts.
        /// </summary>
        public static string codelength {
            get {
                return ResourceManager.GetString("codelength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string ContractTypeDto_ContractTypeFL_Length {
            get {
                return ResourceManager.GetString("ContractTypeDto_ContractTypeFL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string ContractTypeDto_ContractTypeSL_Length {
            get {
                return ResourceManager.GetString("ContractTypeDto_ContractTypeSL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Contract Type already exist.
        /// </summary>
        public static string ContractTypeService_IsExists {
            get {
                return ResourceManager.GetString("ContractTypeService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Not Greater Than 10 Characters.
        /// </summary>
        public static string CountryDto_Code_Length {
            get {
                return ResourceManager.GetString("CountryDto_Code_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string CountryDto_Code_Required {
            get {
                return ResourceManager.GetString("CountryDto_Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string CountryDto_NameFl_Length {
            get {
                return ResourceManager.GetString("CountryDto_NameFl_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string CountryDto_NameSl_Length {
            get {
                return ResourceManager.GetString("CountryDto_NameSl_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Country already exist.
        /// </summary>
        public static string CountryService_IsExists {
            get {
                return ResourceManager.GetString("CountryService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this allowance Date exist .
        /// </summary>
        public static string DateBetweenStartandEnd {
            get {
                return ResourceManager.GetString("DateBetweenStartandEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal IP Already Exist.
        /// </summary>
        public static string DeviceService_IsExists {
            get {
                return ResourceManager.GetString("DeviceService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Not Greater Than 10 Characters.
        /// </summary>
        public static string FullDayPermissionDto_Code_Length {
            get {
                return ResourceManager.GetString("FullDayPermissionDto_Code_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string FullDayPermissionDto_Code_Required {
            get {
                return ResourceManager.GetString("FullDayPermissionDto_Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string FullDayPermissionDto_FullDayPermissionFL_Length {
            get {
                return ResourceManager.GetString("FullDayPermissionDto_FullDayPermissionFL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string FullDayPermissionDto_FullDayPermissionSL_Length {
            get {
                return ResourceManager.GetString("FullDayPermissionDto_FullDayPermissionSL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThisFull Day Permission already exist.
        /// </summary>
        public static string FullDayPermissionService_IsExists {
            get {
                return ResourceManager.GetString("FullDayPermissionService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Holiday Date already exist.
        /// </summary>
        public static string HolidayDateController_IsExists {
            get {
                return ResourceManager.GetString("HolidayDateController_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date Must be Greater Than Or Equal Start Date.
        /// </summary>
        public static string HolidayDateController_ValidateDate {
            get {
                return ResourceManager.GetString("HolidayDateController_ValidateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Id is required.
        /// </summary>
        public static string HolidayDateDto_CountryID {
            get {
                return ResourceManager.GetString("HolidayDateDto_CountryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date is required.
        /// </summary>
        public static string HolidayDateDto_EndDate {
            get {
                return ResourceManager.GetString("HolidayDateDto_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday Id is required.
        /// </summary>
        public static string HolidayDateDto_HolidayID {
            get {
                return ResourceManager.GetString("HolidayDateDto_HolidayID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is required.
        /// </summary>
        public static string HolidayDateDto_StartDate {
            get {
                return ResourceManager.GetString("HolidayDateDto_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Holiday Date Duration for the country is already exist before.
        /// </summary>
        public static string HolidayDateIsExists {
            get {
                return ResourceManager.GetString("HolidayDateIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Not Greater Than 10 Characters.
        /// </summary>
        public static string HolidayDto_Code_Length {
            get {
                return ResourceManager.GetString("HolidayDto_Code_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string HolidayDto_Code_Required {
            get {
                return ResourceManager.GetString("HolidayDto_Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string HolidayDto_PublicHolidayNameFL_Length {
            get {
                return ResourceManager.GetString("HolidayDto_PublicHolidayNameFL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string HolidayDto_PublicHolidayNameSL_Length {
            get {
                return ResourceManager.GetString("HolidayDto_PublicHolidayNameSL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Holiday already exist.
        /// </summary>
        public static string HolidayService_IsExists {
            get {
                return ResourceManager.GetString("HolidayService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string JobDegreeDto_JobDegreeFL_Length {
            get {
                return ResourceManager.GetString("JobDegreeDto_JobDegreeFL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string JobDegreeDto_JobDegreeSL_Length {
            get {
                return ResourceManager.GetString("JobDegreeDto_JobDegreeSL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Job Degree already exist.
        /// </summary>
        public static string JobDegreeService_IsExists {
            get {
                return ResourceManager.GetString("JobDegreeService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string JobDto_Code_Required {
            get {
                return ResourceManager.GetString("JobDto_Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string JobDto_JobFL_Length {
            get {
                return ResourceManager.GetString("JobDto_JobFL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string JobDto_JobSL_Length {
            get {
                return ResourceManager.GetString("JobDto_JobSL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Job already exist.
        /// </summary>
        public static string JobsController_IsExists {
            get {
                return ResourceManager.GetString("JobsController_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Job already exist.
        /// </summary>
        public static string JobService_IsExists {
            get {
                return ResourceManager.GetString("JobService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction Category Is Required.
        /// </summary>
        public static string LateRegulationDeductionDto_DeductionCategoryId_Required {
            get {
                return ResourceManager.GetString("LateRegulationDeductionDto_DeductionCategoryId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction Unit Is Required.
        /// </summary>
        public static string LateRegulationDeductionDto_DeductionUnitId_Required {
            get {
                return ResourceManager.GetString("LateRegulationDeductionDto_DeductionUnitId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance is required.
        /// </summary>
        public static string LateRegulationsDto_Allowance_Required {
            get {
                return ResourceManager.GetString("LateRegulationsDto_Allowance_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction Categore is required.
        /// </summary>
        public static string LateRegulationsDto_DeductionCategoreID_Required {
            get {
                return ResourceManager.GetString("LateRegulationsDto_DeductionCategoreID_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction Group Type is required.
        /// </summary>
        public static string LateRegulationsDto_DeductionGroupTypeID_Required {
            get {
                return ResourceManager.GetString("LateRegulationsDto_DeductionGroupTypeID_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date is required.
        /// </summary>
        public static string LateRegulationsDto_EndDate_Required {
            get {
                return ResourceManager.GetString("LateRegulationsDto_EndDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string LateRegulationsDto_LateRegulationFL_Length {
            get {
                return ResourceManager.GetString("LateRegulationsDto_LateRegulationFL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string LateRegulationsDto_LateRegulationSL_Length {
            get {
                return ResourceManager.GetString("LateRegulationsDto_LateRegulationSL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is required.
        /// </summary>
        public static string LateRegulationsDto_StartDate_Required {
            get {
                return ResourceManager.GetString("LateRegulationsDto_StartDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Regulation Already Exist For All Employees Type In This Period Before.
        /// </summary>
        public static string LateRegulationService_AllEmployeesIsExists {
            get {
                return ResourceManager.GetString("LateRegulationService_AllEmployeesIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Regulation Already Exist For One Of Those Contracts In This Period Before.
        /// </summary>
        public static string LateRegulationService_ContractsIsExists {
            get {
                return ResourceManager.GetString("LateRegulationService_ContractsIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Should Choose Contract First.
        /// </summary>
        public static string LateRegulationService_ContractTypeIsRequired {
            get {
                return ResourceManager.GetString("LateRegulationService_ContractTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Should Choose Deduction Categories First.
        /// </summary>
        public static string LateRegulationService_DeductionIsRequired {
            get {
                return ResourceManager.GetString("LateRegulationService_DeductionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Late Regulation already exist.
        /// </summary>
        public static string LateRegulationService_IsExists {
            get {
                return ResourceManager.GetString("LateRegulationService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length Of Service Is Required.
        /// </summary>
        public static string LateRegulationService_LengthOfServiceIsRequired {
            get {
                return ResourceManager.GetString("LateRegulationService_LengthOfServiceIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Regulation Already Exist For Old Employees Type In This Period Before.
        /// </summary>
        public static string LateRegulationService_OldEmployeesIsExists {
            get {
                return ResourceManager.GetString("LateRegulationService_OldEmployeesIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date Must be Greater Than Or Equal Start Date.
        /// </summary>
        public static string LateRegulationService_ValidateDate {
            get {
                return ResourceManager.GetString("LateRegulationService_ValidateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This LeaveRegulation already exist.
        /// </summary>
        public static string LeaveRegulation_IsExist {
            get {
                return ResourceManager.GetString("LeaveRegulation_IsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Not Greater Than 10 Characters.
        /// </summary>
        public static string LeavesTypesDto_Code_Length {
            get {
                return ResourceManager.GetString("LeavesTypesDto_Code_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string LeavesTypesDto_Code_Required {
            get {
                return ResourceManager.GetString("LeavesTypesDto_Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string LeavesTypesDto_LeaveTypeFL_Length {
            get {
                return ResourceManager.GetString("LeavesTypesDto_LeaveTypeFL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string LeavesTypesDto_LeaveTypeSL_Length {
            get {
                return ResourceManager.GetString("LeavesTypesDto_LeaveTypeSL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Leave Type already exist.
        /// </summary>
        public static string LeavesTypesService_IsExists {
            get {
                return ResourceManager.GetString("LeavesTypesService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Of Service Year Should Be Greater Than Start Of Service.
        /// </summary>
        public static string LengthOfServiceGreaterThan {
            get {
                return ResourceManager.GetString("LengthOfServiceGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Not Greater Than 10 Characters.
        /// </summary>
        public static string LocationDto_Code_Length {
            get {
                return ResourceManager.GetString("LocationDto_Code_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string LocationDto_Code_Required {
            get {
                return ResourceManager.GetString("LocationDto_Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required.
        /// </summary>
        public static string LocationDto_CountryId_Required {
            get {
                return ResourceManager.GetString("LocationDto_CountryId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string LocationDto_LocationFL_Length {
            get {
                return ResourceManager.GetString("LocationDto_LocationFL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string LocationDto_LocationSL_Length {
            get {
                return ResourceManager.GetString("LocationDto_LocationSL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Location already exist.
        /// </summary>
        public static string LocationService_IsExists {
            get {
                return ResourceManager.GetString("LocationService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string NationalityDto_Code_Required {
            get {
                return ResourceManager.GetString("NationalityDto_Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string NationalityDto_NationalityFl_Length {
            get {
                return ResourceManager.GetString("NationalityDto_NationalityFl_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string NationalityDto_NationalitySl_Length {
            get {
                return ResourceManager.GetString("NationalityDto_NationalitySl_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Nationality already exist.
        /// </summary>
        public static string NationalityService_IsExists {
            get {
                return ResourceManager.GetString("NationalityService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Regulation Already Exist In This Period Before.
        /// </summary>
        public static string Organization_Late_Regulation_IsExists {
            get {
                return ResourceManager.GetString("Organization_Late_Regulation_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime Regulation Already Exist In This Period Before.
        /// </summary>
        public static string Overtime_Regulation_IsExists {
            get {
                return ResourceManager.GetString("Overtime_Regulation_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date is required.
        /// </summary>
        public static string OverTimeDateDto_EndDate_Required {
            get {
                return ResourceManager.GetString("OverTimeDateDto_EndDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Period is required.
        /// </summary>
        public static string OverTimeDateDto_EndPeriod_Required {
            get {
                return ResourceManager.GetString("OverTimeDateDto_EndPeriod_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate is required.
        /// </summary>
        public static string OverTimeDateDto_Rate_Required {
            get {
                return ResourceManager.GetString("OverTimeDateDto_Rate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date is required.
        /// </summary>
        public static string OverTimeDateDto_StartDate_Required {
            get {
                return ResourceManager.GetString("OverTimeDateDto_StartDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Period is required.
        /// </summary>
        public static string OverTimeDateDto_StartPeriod_Required {
            get {
                return ResourceManager.GetString("OverTimeDateDto_StartPeriod_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Over Time already exist.
        /// </summary>
        public static string OverTimeDateService_IsExists {
            get {
                return ResourceManager.GetString("OverTimeDateService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning and night can not intersect with each other.
        /// </summary>
        public static string OverTimeDateService_MorningNightTimeIntersect {
            get {
                return ResourceManager.GetString("OverTimeDateService_MorningNightTimeIntersect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date Must be Greater Than Or Equal Start Date.
        /// </summary>
        public static string OverTimeDateService_ValidateDate {
            get {
                return ResourceManager.GetString("OverTimeDateService_ValidateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Not Greater Than 6 Characters.
        /// </summary>
        public static string PartialPermissionTypeDto_Code_Length {
            get {
                return ResourceManager.GetString("PartialPermissionTypeDto_Code_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string PartialPermissionTypeDto_Code_Required {
            get {
                return ResourceManager.GetString("PartialPermissionTypeDto_Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required.
        /// </summary>
        public static string PartialPermissionTypeDto_CountryId_Required {
            get {
                return ResourceManager.GetString("PartialPermissionTypeDto_CountryId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string PartialPermissionTypeDto_PartialPermissionFL_Length {
            get {
                return ResourceManager.GetString("PartialPermissionTypeDto_PartialPermissionFL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string PartialPermissionTypeDto_PartialPermissionSL_Length {
            get {
                return ResourceManager.GetString("PartialPermissionTypeDto_PartialPermissionSL_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Partial Permission Type already exist.
        /// </summary>
        public static string PartialPermissionTypeService_IsExists {
            get {
                return ResourceManager.GetString("PartialPermissionTypeService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string QualificationDto_QualificationTypeFl_Length {
            get {
                return ResourceManager.GetString("QualificationDto_QualificationTypeFl_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string QualificationDto_QualificationTypeSl_Length {
            get {
                return ResourceManager.GetString("QualificationDto_QualificationTypeSl_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Qualification already exist.
        /// </summary>
        public static string QualificationService_IsExists {
            get {
                return ResourceManager.GetString("QualificationService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Not Greater Than 10 Characters.
        /// </summary>
        public static string ReligionDto_Code_Length {
            get {
                return ResourceManager.GetString("ReligionDto_Code_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required.
        /// </summary>
        public static string ReligionDto_Code_Required {
            get {
                return ResourceManager.GetString("ReligionDto_Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string ReligionDto_DescriptionFl_Length {
            get {
                return ResourceManager.GetString("ReligionDto_DescriptionFl_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string ReligionDto_DescriptionSl_Length {
            get {
                return ResourceManager.GetString("ReligionDto_DescriptionSl_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Religion already exist.
        /// </summary>
        public static string ReligionService_IsExists {
            get {
                return ResourceManager.GetString("ReligionService_IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string TeamDto_TeamFl_Length {
            get {
                return ResourceManager.GetString("TeamDto_TeamFl_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Lang Not Greater Than 200 Characters.
        /// </summary>
        public static string TeamDto_TeamSl_Length {
            get {
                return ResourceManager.GetString("TeamDto_TeamSl_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Team already exist.
        /// </summary>
        public static string TeamService_IsExists {
            get {
                return ResourceManager.GetString("TeamService_IsExists", resourceCulture);
            }
        }
    }
}
